"""add_group_id_to_events

Revision ID: 0bc2a1184263
Revises: eddec35a6940
Create Date: 2026-01-04 14:20:09.568901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc2a1184263'
down_revision: Union[str, None] = 'eddec35a6940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('group_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_events_group_id'), 'events', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_group_id'), table_name='events')
    op.drop_column('events', 'group_id')
    # ### end Alembic commands ###
