"""Add bueskyting_id to archer_profiles

Revision ID: 7c46ddbe8345
Revises: 8cf7cfe58fe5
Create Date: 2026-03-15 09:15:00.512200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c46ddbe8345'
down_revision: Union[str, None] = '8cf7cfe58fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archer_profiles', sa.Column('bueskyting_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_archer_profiles_bueskyting_id'), 'archer_profiles', ['bueskyting_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archer_profiles_bueskyting_id'), table_name='archer_profiles')
    op.drop_column('archer_profiles', 'bueskyting_id')
    # ### end Alembic commands ###
