"""add group_members association table

Revision ID: e7a91b3c2d10
Revises: db150f900da8
Create Date: 2026-05-13 09:00:00.000000

Converts members<->groups from a single FK (members.group_id) to a many-to-many
association via group_members. Per-group role_uids and subgroup_uids move onto
the association row.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a91b3c2d10'
down_revision: Union[str, None] = 'db150f900da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create the join table.
    op.create_table(
        'group_members',
        sa.Column('member_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('role_uids', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
        sa.Column('subgroup_uids', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
        sa.Column('last_synced_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('member_id', 'group_id'),
    )
    op.create_index('ix_group_members_member_id', 'group_members', ['member_id'])
    op.create_index('ix_group_members_group_id', 'group_members', ['group_id'])

    # 2. Backfill from existing members.group_id (FK was to groups.spond_id).
    op.execute(
        """
        INSERT INTO group_members (member_id, group_id, role_uids, subgroup_uids, last_synced_at, created_at, updated_at)
        SELECT m.id,
               g.id,
               COALESCE(m.role_uids, '[]'::json),
               COALESCE(m.subgroup_uids, '[]'::json),
               COALESCE(m.last_synced_at, NOW()),
               NOW(),
               NOW()
          FROM members m
          JOIN groups g ON g.spond_id = m.group_id
         WHERE m.group_id IS NOT NULL
        ON CONFLICT (member_id, group_id) DO NOTHING;
        """
    )

    # 3. Drop the old single-FK column and friends. Look up FK constraint name
    #    dynamically so we don't depend on autogenerated names that differ
    #    across environments.
    bind = op.get_bind()
    fk_name = bind.execute(
        sa.text(
            """
            SELECT tc.constraint_name
              FROM information_schema.table_constraints tc
              JOIN information_schema.key_column_usage kcu
                ON tc.constraint_name = kcu.constraint_name
             WHERE tc.table_name = 'members'
               AND tc.constraint_type = 'FOREIGN KEY'
               AND kcu.column_name = 'group_id'
             LIMIT 1
            """
        )
    ).scalar()
    if fk_name:
        op.drop_constraint(fk_name, 'members', type_='foreignkey')

    op.drop_column('members', 'group_id')
    op.drop_column('members', 'role_uids')
    op.drop_column('members', 'subgroup_uids')


def downgrade() -> None:
    # Restore the dropped columns.
    op.add_column('members', sa.Column('group_id', sa.String(length=255), nullable=True))
    op.add_column('members', sa.Column('role_uids', sa.JSON(), nullable=True))
    op.add_column('members', sa.Column('subgroup_uids', sa.JSON(), nullable=True))
    op.create_foreign_key(
        'members_group_id_fkey',
        'members',
        'groups',
        ['group_id'],
        ['spond_id'],
    )

    # Backfill the single FK + per-group fields from the most recent association.
    op.execute(
        """
        UPDATE members m
           SET group_id = sub.spond_id,
               role_uids = sub.role_uids,
               subgroup_uids = sub.subgroup_uids
          FROM (
              SELECT DISTINCT ON (gm.member_id)
                     gm.member_id,
                     g.spond_id,
                     gm.role_uids,
                     gm.subgroup_uids
                FROM group_members gm
                JOIN groups g ON g.id = gm.group_id
               ORDER BY gm.member_id, gm.last_synced_at DESC
          ) sub
         WHERE m.id = sub.member_id;
        """
    )

    op.drop_index('ix_group_members_group_id', table_name='group_members')
    op.drop_index('ix_group_members_member_id', table_name='group_members')
    op.drop_table('group_members')
